export const FETCH_ALL_PROJECT_REQUEST = "FETCH_ALL_PROJECT_REQUEST";
export const FETCH_ALL_PROJECT_SUCCESS = "FETCH_ALL_PROJECT_SUCCESS";
export const FETCH_ALL_PROJECT_FAIL = "FETCH_ALL_PROJECT_FAIL";

export const SEARCH_PROJECT_REQUEST = "FETCH_ALL_PROJECT_REQUEST";
export const SEARCH_PROJECT_SUCCESS = "FETCH_ALL_PROJECT_SUCCESS";
export const SEARCH_PROJECT_FAIL = "FETCH_ALL_PROJECT_FAIL";

export const PROJECT_DETAILS_REQUEST = "PROJECT_DETAILS_REQUEST";
export const PROJECT_DETAILS_SUCCESS = "PROJECT_DETAILS_SUCCESS";
export const PROJECT_DETAILS_FAIL = "PROJECT_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
